export const localization = {
  en: {
    remember: 'Remember',
    me: 'Me',
    buttons: {
      addWord: 'Add Word',
      repeatWords: 'Repeat Words',
      repeatTranslations: 'Repeat Translations',
      close: 'Close',
      yes: 'Yes',
      add: 'Add',
      delete: 'Delete',
      cancel: 'Cancel',
      ok: 'Ok'
    },
    checkAll: 'Check all',
    addWord: 'Word adding',
    dictionaries: 'Dictionaries',
    dictionary: 'Dictionary',
    selectDictionaries: 'Select dictionaries',
    repeatWords: 'Repeat words',
    theWord: 'The Word',
    dictionaryName: 'Name of a dictionary',
    theTranslation: 'The Translation',
    iLearned: 'I Learned!',
    noWordsLeft: 'No words left! You passed them all.',
    allDictionaryWordsWillBeDeleted: 'All words from dictionary will be deleted.',
    noDictionariesCreated: 'There are no dictionaries created',
    createDictionaryFirst: 'Create dictionary first',
    areYouSure: 'Are you sure?',
    errors: {
      fillTheFields: 'Fill the fields!',
      cannotAddWordToDB: 'Cant add word to db!',
    },
    snackbars: {
      wordAdded: 'Word added!',
      dictionaryAdded: 'Dictionary added!',
      dictionaryDeleted: 'Dictionary deleted!',
    },
    guessed: 'Correct: {{count}}'
  },
  ru: {
    remember: 'Запомни',
    me: 'Меня',
    buttons: {
      addWord: 'Добавить слово',
      repeatWords: 'Повторить слова',
      repeatTranslations: 'Повторить переводы',
      close: 'Закрыть',
      yes: 'Да',
      add: 'Добавить',
      delete: 'Удалить',
      cancel: 'Отмена',
      ok: 'Ок'
    },
    checkAll: 'Выбрать все',
    addWord: 'Добавление слова',
    dictionaries: 'Словари',
    dictionary: 'Словарь ',
    selectDictionaries: 'Выбор словарей',
    repeatWords: 'Повторение слов',
    theWord: 'Слово',
    dictionaryName: 'Название словаря',
    theTranslation: 'Перевод',
    iLearned: 'Я Выучил!',
    noWordsLeft: 'Не осталось слов! Вы все повторили.',
    allDictionaryWordsWillBeDeleted: 'Все слова из словаря будут удалены.',
    noDictionariesCreated: 'Нет созданных словарей',
    createDictionaryFirst: 'Создайте словарь',
    areYouSure: 'Вы уверены?',
    errors: {
      fillTheFields: 'Заполните поля!',
      cannotAddWordToDB: 'Не удалось добавить запись в бд!',
    },
    snackbars: {
      wordAdded: 'Слово сохранено!',
      dictionaryAdded: 'Словарь добавлен!',
      dictionaryDeleted: 'Словарь удален!',
    },
    guessed: 'Правильно: {{count}}'
  },
};